-- migrations/002_seed_challenges.sql
-- Seed data for ARRL WAS 250 and DXCC challenges

-- ARRL WAS 250 (2026 only, no historical QSOs)
INSERT INTO challenges (
    id,
    version,
    name,
    description,
    author,
    category,
    challenge_type,
    configuration,
    is_active
) VALUES (
    'a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d',
    1,
    'ARRL WAS 250',
    'Work all 50 US states during 2026 to celebrate the 250th anniversary of American independence. Only QSOs made in 2026 count toward this challenge.',
    'ARRL',
    'award',
    'collection',
    '{
        "goals": {
            "type": "collection",
            "items": [
                {"id": "AL", "name": "Alabama", "category": "state"},
                {"id": "AK", "name": "Alaska", "category": "state"},
                {"id": "AZ", "name": "Arizona", "category": "state"},
                {"id": "AR", "name": "Arkansas", "category": "state"},
                {"id": "CA", "name": "California", "category": "state"},
                {"id": "CO", "name": "Colorado", "category": "state"},
                {"id": "CT", "name": "Connecticut", "category": "state"},
                {"id": "DE", "name": "Delaware", "category": "state"},
                {"id": "FL", "name": "Florida", "category": "state"},
                {"id": "GA", "name": "Georgia", "category": "state"},
                {"id": "HI", "name": "Hawaii", "category": "state"},
                {"id": "ID", "name": "Idaho", "category": "state"},
                {"id": "IL", "name": "Illinois", "category": "state"},
                {"id": "IN", "name": "Indiana", "category": "state"},
                {"id": "IA", "name": "Iowa", "category": "state"},
                {"id": "KS", "name": "Kansas", "category": "state"},
                {"id": "KY", "name": "Kentucky", "category": "state"},
                {"id": "LA", "name": "Louisiana", "category": "state"},
                {"id": "ME", "name": "Maine", "category": "state"},
                {"id": "MD", "name": "Maryland", "category": "state"},
                {"id": "MA", "name": "Massachusetts", "category": "state"},
                {"id": "MI", "name": "Michigan", "category": "state"},
                {"id": "MN", "name": "Minnesota", "category": "state"},
                {"id": "MS", "name": "Mississippi", "category": "state"},
                {"id": "MO", "name": "Missouri", "category": "state"},
                {"id": "MT", "name": "Montana", "category": "state"},
                {"id": "NE", "name": "Nebraska", "category": "state"},
                {"id": "NV", "name": "Nevada", "category": "state"},
                {"id": "NH", "name": "New Hampshire", "category": "state"},
                {"id": "NJ", "name": "New Jersey", "category": "state"},
                {"id": "NM", "name": "New Mexico", "category": "state"},
                {"id": "NY", "name": "New York", "category": "state"},
                {"id": "NC", "name": "North Carolina", "category": "state"},
                {"id": "ND", "name": "North Dakota", "category": "state"},
                {"id": "OH", "name": "Ohio", "category": "state"},
                {"id": "OK", "name": "Oklahoma", "category": "state"},
                {"id": "OR", "name": "Oregon", "category": "state"},
                {"id": "PA", "name": "Pennsylvania", "category": "state"},
                {"id": "RI", "name": "Rhode Island", "category": "state"},
                {"id": "SC", "name": "South Carolina", "category": "state"},
                {"id": "SD", "name": "South Dakota", "category": "state"},
                {"id": "TN", "name": "Tennessee", "category": "state"},
                {"id": "TX", "name": "Texas", "category": "state"},
                {"id": "UT", "name": "Utah", "category": "state"},
                {"id": "VT", "name": "Vermont", "category": "state"},
                {"id": "VA", "name": "Virginia", "category": "state"},
                {"id": "WA", "name": "Washington", "category": "state"},
                {"id": "WV", "name": "West Virginia", "category": "state"},
                {"id": "WI", "name": "Wisconsin", "category": "state"},
                {"id": "WY", "name": "Wyoming", "category": "state"}
            ]
        },
        "timeConstraints": {
            "type": "calendar",
            "startDate": "2026-01-01T00:00:00Z",
            "endDate": "2026-12-31T23:59:59Z",
            "timezone": "UTC"
        },
        "qualificationCriteria": {
            "bands": null,
            "modes": null,
            "requiredFields": [],
            "dateRange": {
                "start": "2026-01-01T00:00:00Z",
                "end": "2026-12-31T23:59:59Z"
            },
            "matchRules": [
                {
                    "qsoField": "state",
                    "goalField": "id",
                    "transformation": "uppercase"
                }
            ]
        },
        "historicalQsosAllowed": false,
        "scoring": {
            "method": "count",
            "tiebreaker": "earliestCompletion",
            "displayFormat": "{value}/50 states"
        }
    }',
    true
)
ON CONFLICT (id) DO NOTHING;

-- DXCC (all-time, with tiers, historical QSOs allowed)
INSERT INTO challenges (
    id,
    version,
    name,
    description,
    author,
    category,
    challenge_type,
    configuration,
    is_active
) VALUES (
    'b2c3d4e5-f6a7-5b6c-9d0e-1f2a3b4c5d6e',
    1,
    'DXCC',
    'Work 100 or more DXCC entities to earn the DX Century Club award. All confirmed QSOs count, regardless of when they were made.',
    'ARRL',
    'award',
    'collection',
    '{
        "goals": {
            "type": "collection",
            "items": [
                {"id": "1", "name": "Canada", "category": "dxcc"},
                {"id": "3", "name": "Afghanistan", "category": "dxcc"},
                {"id": "4", "name": "Agalega & St. Brandon Is.", "category": "dxcc"},
                {"id": "5", "name": "Aland Is.", "category": "dxcc"},
                {"id": "6", "name": "Alaska", "category": "dxcc"},
                {"id": "7", "name": "Albania", "category": "dxcc"},
                {"id": "9", "name": "American Samoa", "category": "dxcc"},
                {"id": "10", "name": "Amsterdam & St. Paul Is.", "category": "dxcc"},
                {"id": "11", "name": "Andaman & Nicobar Is.", "category": "dxcc"},
                {"id": "12", "name": "Anguilla", "category": "dxcc"},
                {"id": "13", "name": "Antarctica", "category": "dxcc"},
                {"id": "14", "name": "Armenia", "category": "dxcc"},
                {"id": "15", "name": "Asiatic Russia", "category": "dxcc"},
                {"id": "16", "name": "New Zealand Subantarctic Islands", "category": "dxcc"},
                {"id": "17", "name": "Aves I.", "category": "dxcc"},
                {"id": "18", "name": "Azerbaijan", "category": "dxcc"},
                {"id": "20", "name": "Baker & Howland Is.", "category": "dxcc"},
                {"id": "21", "name": "Balearic Is.", "category": "dxcc"},
                {"id": "22", "name": "Palau", "category": "dxcc"},
                {"id": "24", "name": "Bouvet", "category": "dxcc"},
                {"id": "27", "name": "Belarus", "category": "dxcc"},
                {"id": "29", "name": "Canary Is.", "category": "dxcc"},
                {"id": "31", "name": "C. Kiribati", "category": "dxcc"},
                {"id": "32", "name": "Ceuta & Melilla", "category": "dxcc"},
                {"id": "33", "name": "Chagos Is.", "category": "dxcc"},
                {"id": "34", "name": "Chatham Is.", "category": "dxcc"},
                {"id": "35", "name": "Christmas I.", "category": "dxcc"},
                {"id": "36", "name": "Clipperton I.", "category": "dxcc"},
                {"id": "37", "name": "Cocos I.", "category": "dxcc"},
                {"id": "38", "name": "Cocos (Keeling) Is.", "category": "dxcc"},
                {"id": "40", "name": "Crete", "category": "dxcc"},
                {"id": "41", "name": "Crozet I.", "category": "dxcc"},
                {"id": "43", "name": "Desecheo I.", "category": "dxcc"},
                {"id": "45", "name": "Dodecanese", "category": "dxcc"},
                {"id": "46", "name": "East Malaysia", "category": "dxcc"},
                {"id": "47", "name": "Easter I.", "category": "dxcc"},
                {"id": "48", "name": "E. Kiribati", "category": "dxcc"},
                {"id": "49", "name": "Equatorial Guinea", "category": "dxcc"},
                {"id": "50", "name": "Mexico", "category": "dxcc"},
                {"id": "51", "name": "Eritrea", "category": "dxcc"},
                {"id": "52", "name": "Estonia", "category": "dxcc"},
                {"id": "53", "name": "Ethiopia", "category": "dxcc"},
                {"id": "54", "name": "European Russia", "category": "dxcc"},
                {"id": "56", "name": "Fernando de Noronha", "category": "dxcc"},
                {"id": "60", "name": "Bahamas", "category": "dxcc"},
                {"id": "61", "name": "Franz Josef Land", "category": "dxcc"},
                {"id": "62", "name": "Barbados", "category": "dxcc"},
                {"id": "63", "name": "French Guiana", "category": "dxcc"},
                {"id": "64", "name": "Bermuda", "category": "dxcc"},
                {"id": "65", "name": "British Virgin Is.", "category": "dxcc"},
                {"id": "66", "name": "Belize", "category": "dxcc"},
                {"id": "69", "name": "Cayman Is.", "category": "dxcc"},
                {"id": "70", "name": "Cuba", "category": "dxcc"},
                {"id": "71", "name": "Galapagos Is.", "category": "dxcc"},
                {"id": "72", "name": "Dominican Republic", "category": "dxcc"},
                {"id": "74", "name": "El Salvador", "category": "dxcc"},
                {"id": "75", "name": "Georgia", "category": "dxcc"},
                {"id": "76", "name": "Guatemala", "category": "dxcc"},
                {"id": "77", "name": "Grenada", "category": "dxcc"},
                {"id": "78", "name": "Haiti", "category": "dxcc"},
                {"id": "79", "name": "Guadeloupe", "category": "dxcc"},
                {"id": "80", "name": "Honduras", "category": "dxcc"},
                {"id": "82", "name": "Jamaica", "category": "dxcc"},
                {"id": "84", "name": "Martinique", "category": "dxcc"},
                {"id": "86", "name": "Nicaragua", "category": "dxcc"},
                {"id": "88", "name": "Panama", "category": "dxcc"},
                {"id": "89", "name": "Turks & Caicos Is.", "category": "dxcc"},
                {"id": "90", "name": "Trinidad & Tobago", "category": "dxcc"},
                {"id": "91", "name": "Aruba", "category": "dxcc"},
                {"id": "94", "name": "Antigua & Barbuda", "category": "dxcc"},
                {"id": "95", "name": "Dominica", "category": "dxcc"},
                {"id": "96", "name": "Montserrat", "category": "dxcc"},
                {"id": "97", "name": "St. Lucia", "category": "dxcc"},
                {"id": "98", "name": "St. Vincent", "category": "dxcc"},
                {"id": "99", "name": "Glorioso Is.", "category": "dxcc"},
                {"id": "100", "name": "Argentina", "category": "dxcc"},
                {"id": "103", "name": "Guam", "category": "dxcc"},
                {"id": "104", "name": "Bolivia", "category": "dxcc"},
                {"id": "105", "name": "Guantanamo Bay", "category": "dxcc"},
                {"id": "106", "name": "Guernsey", "category": "dxcc"},
                {"id": "107", "name": "Guinea", "category": "dxcc"},
                {"id": "108", "name": "Brazil", "category": "dxcc"},
                {"id": "109", "name": "Guinea-Bissau", "category": "dxcc"},
                {"id": "110", "name": "Hawaii", "category": "dxcc"},
                {"id": "111", "name": "Heard I.", "category": "dxcc"},
                {"id": "112", "name": "Chile", "category": "dxcc"},
                {"id": "114", "name": "Isle of Man", "category": "dxcc"},
                {"id": "116", "name": "Colombia", "category": "dxcc"},
                {"id": "117", "name": "ITU HQ", "category": "dxcc"},
                {"id": "118", "name": "Jan Mayen", "category": "dxcc"},
                {"id": "120", "name": "Ecuador", "category": "dxcc"},
                {"id": "122", "name": "Jersey", "category": "dxcc"},
                {"id": "123", "name": "Johnston I.", "category": "dxcc"},
                {"id": "124", "name": "Juan de Nova & Europa", "category": "dxcc"},
                {"id": "125", "name": "Juan Fernandez Is.", "category": "dxcc"},
                {"id": "126", "name": "Kaliningrad", "category": "dxcc"},
                {"id": "129", "name": "Guyana", "category": "dxcc"},
                {"id": "130", "name": "Kazakhstan", "category": "dxcc"},
                {"id": "131", "name": "Kerguelen Is.", "category": "dxcc"},
                {"id": "132", "name": "Paraguay", "category": "dxcc"},
                {"id": "133", "name": "Kermadec Is.", "category": "dxcc"},
                {"id": "135", "name": "Kyrgyz Republic", "category": "dxcc"},
                {"id": "136", "name": "Peru", "category": "dxcc"},
                {"id": "137", "name": "Republic of Korea", "category": "dxcc"},
                {"id": "138", "name": "Kure I.", "category": "dxcc"},
                {"id": "140", "name": "Suriname", "category": "dxcc"},
                {"id": "141", "name": "Falkland Is.", "category": "dxcc"},
                {"id": "142", "name": "Lakshadweep Is.", "category": "dxcc"},
                {"id": "143", "name": "Lao People''s Dem Repub", "category": "dxcc"},
                {"id": "144", "name": "Uruguay", "category": "dxcc"},
                {"id": "145", "name": "Latvia", "category": "dxcc"},
                {"id": "146", "name": "Lithuania", "category": "dxcc"},
                {"id": "147", "name": "Lord Howe I.", "category": "dxcc"},
                {"id": "148", "name": "Venezuela", "category": "dxcc"},
                {"id": "149", "name": "Azores", "category": "dxcc"},
                {"id": "150", "name": "Australia", "category": "dxcc"},
                {"id": "152", "name": "Macao", "category": "dxcc"},
                {"id": "153", "name": "Macquarie I.", "category": "dxcc"},
                {"id": "157", "name": "Nauru", "category": "dxcc"},
                {"id": "158", "name": "Vanuatu", "category": "dxcc"},
                {"id": "159", "name": "Maldives", "category": "dxcc"},
                {"id": "160", "name": "Tonga", "category": "dxcc"},
                {"id": "161", "name": "Malpelo I.", "category": "dxcc"},
                {"id": "163", "name": "Papua New Guinea", "category": "dxcc"},
                {"id": "165", "name": "Mauritius", "category": "dxcc"},
                {"id": "166", "name": "Mariana Is.", "category": "dxcc"},
                {"id": "167", "name": "Market Reef", "category": "dxcc"},
                {"id": "168", "name": "Marshall Is.", "category": "dxcc"},
                {"id": "169", "name": "Mayotte", "category": "dxcc"},
                {"id": "170", "name": "New Zealand", "category": "dxcc"},
                {"id": "171", "name": "Mellish Reef", "category": "dxcc"},
                {"id": "172", "name": "Pitcairn I.", "category": "dxcc"},
                {"id": "173", "name": "Micronesia", "category": "dxcc"},
                {"id": "174", "name": "Midway I.", "category": "dxcc"},
                {"id": "175", "name": "French Polynesia", "category": "dxcc"},
                {"id": "176", "name": "Fiji", "category": "dxcc"},
                {"id": "177", "name": "Minami Torishima", "category": "dxcc"},
                {"id": "179", "name": "Moldova", "category": "dxcc"},
                {"id": "180", "name": "Mount Athos", "category": "dxcc"},
                {"id": "181", "name": "Mozambique", "category": "dxcc"},
                {"id": "182", "name": "Navassa I.", "category": "dxcc"},
                {"id": "185", "name": "Solomon Is.", "category": "dxcc"},
                {"id": "187", "name": "Niger", "category": "dxcc"},
                {"id": "188", "name": "Niue", "category": "dxcc"},
                {"id": "189", "name": "Norfolk I.", "category": "dxcc"},
                {"id": "190", "name": "Samoa", "category": "dxcc"},
                {"id": "191", "name": "N. Cook Is.", "category": "dxcc"},
                {"id": "192", "name": "Ogasawara", "category": "dxcc"},
                {"id": "195", "name": "Annobon I.", "category": "dxcc"},
                {"id": "197", "name": "Palmyra & Jarvis Is.", "category": "dxcc"},
                {"id": "199", "name": "Peter 1 I.", "category": "dxcc"},
                {"id": "201", "name": "Prince Edward & Marion Is.", "category": "dxcc"},
                {"id": "202", "name": "Puerto Rico", "category": "dxcc"},
                {"id": "203", "name": "Andorra", "category": "dxcc"},
                {"id": "204", "name": "Revillagigedo", "category": "dxcc"},
                {"id": "205", "name": "Ascension I.", "category": "dxcc"},
                {"id": "206", "name": "Austria", "category": "dxcc"},
                {"id": "207", "name": "Rodrigues I.", "category": "dxcc"},
                {"id": "209", "name": "Belgium", "category": "dxcc"},
                {"id": "211", "name": "Sable I.", "category": "dxcc"},
                {"id": "212", "name": "Bulgaria", "category": "dxcc"},
                {"id": "213", "name": "Saint Martin", "category": "dxcc"},
                {"id": "214", "name": "Corsica", "category": "dxcc"},
                {"id": "215", "name": "Cyprus", "category": "dxcc"},
                {"id": "216", "name": "San Andres & Providencia", "category": "dxcc"},
                {"id": "217", "name": "San Felix & San Ambrosio", "category": "dxcc"},
                {"id": "219", "name": "Sao Tome & Principe", "category": "dxcc"},
                {"id": "221", "name": "Denmark", "category": "dxcc"},
                {"id": "222", "name": "Faroe Is.", "category": "dxcc"},
                {"id": "223", "name": "United Kingdom of Great Britain & Northern Ireland", "category": "dxcc"},
                {"id": "224", "name": "Finland", "category": "dxcc"},
                {"id": "225", "name": "Sardinia", "category": "dxcc"},
                {"id": "227", "name": "France", "category": "dxcc"},
                {"id": "230", "name": "Germany", "category": "dxcc"},
                {"id": "232", "name": "Somalia", "category": "dxcc"},
                {"id": "233", "name": "Gibraltar", "category": "dxcc"},
                {"id": "234", "name": "S. Cook Is.", "category": "dxcc"},
                {"id": "235", "name": "South Georgia I.", "category": "dxcc"},
                {"id": "236", "name": "Greece", "category": "dxcc"},
                {"id": "237", "name": "Greenland", "category": "dxcc"},
                {"id": "238", "name": "South Orkney Is.", "category": "dxcc"},
                {"id": "239", "name": "Hungary", "category": "dxcc"},
                {"id": "240", "name": "South Sandwich Is.", "category": "dxcc"},
                {"id": "241", "name": "South Shetland Is.", "category": "dxcc"},
                {"id": "242", "name": "Iceland", "category": "dxcc"},
                {"id": "245", "name": "Ireland", "category": "dxcc"},
                {"id": "246", "name": "Sov. Mil. Order of Malta", "category": "dxcc"},
                {"id": "247", "name": "Spratly Is.", "category": "dxcc"},
                {"id": "248", "name": "Italy", "category": "dxcc"},
                {"id": "249", "name": "St. Kitts & Nevis", "category": "dxcc"},
                {"id": "250", "name": "St. Helena", "category": "dxcc"},
                {"id": "251", "name": "Liechtenstein", "category": "dxcc"},
                {"id": "252", "name": "St. Paul I.", "category": "dxcc"},
                {"id": "253", "name": "St. Peter & St. Paul Rocks", "category": "dxcc"},
                {"id": "254", "name": "Luxembourg", "category": "dxcc"},
                {"id": "256", "name": "Madeira Is.", "category": "dxcc"},
                {"id": "257", "name": "Malta", "category": "dxcc"},
                {"id": "259", "name": "Svalbard", "category": "dxcc"},
                {"id": "260", "name": "Monaco", "category": "dxcc"},
                {"id": "262", "name": "Tajikistan", "category": "dxcc"},
                {"id": "263", "name": "Netherlands", "category": "dxcc"},
                {"id": "265", "name": "Northern Ireland", "category": "dxcc"},
                {"id": "266", "name": "Norway", "category": "dxcc"},
                {"id": "269", "name": "Poland", "category": "dxcc"},
                {"id": "270", "name": "Tokelau Is.", "category": "dxcc"},
                {"id": "272", "name": "Portugal", "category": "dxcc"},
                {"id": "273", "name": "Trindade & Martim Vaz Is.", "category": "dxcc"},
                {"id": "274", "name": "Tristan da Cunha & Gough I.", "category": "dxcc"},
                {"id": "275", "name": "Romania", "category": "dxcc"},
                {"id": "276", "name": "Tromelin I.", "category": "dxcc"},
                {"id": "277", "name": "St. Pierre & Miquelon", "category": "dxcc"},
                {"id": "278", "name": "San Marino", "category": "dxcc"},
                {"id": "279", "name": "Scotland", "category": "dxcc"},
                {"id": "280", "name": "Turkmenistan", "category": "dxcc"},
                {"id": "281", "name": "Spain", "category": "dxcc"},
                {"id": "282", "name": "Tuvalu", "category": "dxcc"},
                {"id": "283", "name": "UK Sov. Base Areas on Cyprus", "category": "dxcc"},
                {"id": "284", "name": "Sweden", "category": "dxcc"},
                {"id": "285", "name": "Virgin Is.", "category": "dxcc"},
                {"id": "286", "name": "Uganda", "category": "dxcc"},
                {"id": "287", "name": "Switzerland", "category": "dxcc"},
                {"id": "288", "name": "Ukraine", "category": "dxcc"},
                {"id": "289", "name": "United Nations HQ", "category": "dxcc"},
                {"id": "291", "name": "United States of America", "category": "dxcc"},
                {"id": "292", "name": "Uzbekistan", "category": "dxcc"},
                {"id": "293", "name": "Viet Nam", "category": "dxcc"},
                {"id": "294", "name": "Wales", "category": "dxcc"},
                {"id": "295", "name": "Vatican", "category": "dxcc"},
                {"id": "296", "name": "Serbia", "category": "dxcc"},
                {"id": "297", "name": "Wake I.", "category": "dxcc"},
                {"id": "298", "name": "Wallis & Futuna Is.", "category": "dxcc"},
                {"id": "299", "name": "West Malaysia", "category": "dxcc"},
                {"id": "301", "name": "W. Kiribati", "category": "dxcc"},
                {"id": "302", "name": "Western Sahara", "category": "dxcc"},
                {"id": "303", "name": "Willis I.", "category": "dxcc"},
                {"id": "304", "name": "Bahrain", "category": "dxcc"},
                {"id": "305", "name": "Bangladesh", "category": "dxcc"},
                {"id": "306", "name": "Bhutan", "category": "dxcc"},
                {"id": "308", "name": "Costa Rica", "category": "dxcc"},
                {"id": "309", "name": "Myanmar", "category": "dxcc"},
                {"id": "312", "name": "Cambodia", "category": "dxcc"},
                {"id": "315", "name": "Sri Lanka", "category": "dxcc"},
                {"id": "318", "name": "China", "category": "dxcc"},
                {"id": "321", "name": "Hong Kong", "category": "dxcc"},
                {"id": "324", "name": "India", "category": "dxcc"},
                {"id": "327", "name": "Indonesia", "category": "dxcc"},
                {"id": "330", "name": "Iran", "category": "dxcc"},
                {"id": "333", "name": "Iraq", "category": "dxcc"},
                {"id": "336", "name": "Israel", "category": "dxcc"},
                {"id": "339", "name": "Japan", "category": "dxcc"},
                {"id": "342", "name": "Jordan", "category": "dxcc"},
                {"id": "344", "name": "DPR of Korea", "category": "dxcc"},
                {"id": "345", "name": "Brunei Darussalam", "category": "dxcc"},
                {"id": "348", "name": "Kuwait", "category": "dxcc"},
                {"id": "354", "name": "Lebanon", "category": "dxcc"},
                {"id": "363", "name": "Mongolia", "category": "dxcc"},
                {"id": "369", "name": "Nepal", "category": "dxcc"},
                {"id": "370", "name": "Oman", "category": "dxcc"},
                {"id": "372", "name": "Pakistan", "category": "dxcc"},
                {"id": "375", "name": "Philippines", "category": "dxcc"},
                {"id": "376", "name": "Qatar", "category": "dxcc"},
                {"id": "378", "name": "Saudi Arabia", "category": "dxcc"},
                {"id": "379", "name": "Seychelles", "category": "dxcc"},
                {"id": "381", "name": "Singapore", "category": "dxcc"},
                {"id": "382", "name": "Djibouti", "category": "dxcc"},
                {"id": "384", "name": "Syrian Arab Republic", "category": "dxcc"},
                {"id": "386", "name": "Taiwan", "category": "dxcc"},
                {"id": "387", "name": "Thailand", "category": "dxcc"},
                {"id": "390", "name": "Republic of Turkiye", "category": "dxcc"},
                {"id": "391", "name": "United Arab Emirates", "category": "dxcc"},
                {"id": "400", "name": "Algeria", "category": "dxcc"},
                {"id": "401", "name": "Angola", "category": "dxcc"},
                {"id": "402", "name": "Botswana", "category": "dxcc"},
                {"id": "404", "name": "Burundi", "category": "dxcc"},
                {"id": "406", "name": "Cameroon", "category": "dxcc"},
                {"id": "408", "name": "Central Africa", "category": "dxcc"},
                {"id": "409", "name": "Cabo Verde", "category": "dxcc"},
                {"id": "410", "name": "Chad", "category": "dxcc"},
                {"id": "411", "name": "Comoros", "category": "dxcc"},
                {"id": "412", "name": "Congo", "category": "dxcc"},
                {"id": "414", "name": "Dem. Rep. of the Congo", "category": "dxcc"},
                {"id": "416", "name": "Benin", "category": "dxcc"},
                {"id": "420", "name": "Gabon", "category": "dxcc"},
                {"id": "422", "name": "Gambia", "category": "dxcc"},
                {"id": "424", "name": "Ghana", "category": "dxcc"},
                {"id": "428", "name": "Cote d''Ivoire", "category": "dxcc"},
                {"id": "430", "name": "Kenya", "category": "dxcc"},
                {"id": "432", "name": "Lesotho", "category": "dxcc"},
                {"id": "434", "name": "Liberia", "category": "dxcc"},
                {"id": "436", "name": "Libya", "category": "dxcc"},
                {"id": "438", "name": "Madagascar", "category": "dxcc"},
                {"id": "440", "name": "Malawi", "category": "dxcc"},
                {"id": "442", "name": "Mali", "category": "dxcc"},
                {"id": "444", "name": "Mauritania", "category": "dxcc"},
                {"id": "446", "name": "Morocco", "category": "dxcc"},
                {"id": "450", "name": "Nigeria", "category": "dxcc"},
                {"id": "452", "name": "Zimbabwe", "category": "dxcc"},
                {"id": "453", "name": "Reunion I.", "category": "dxcc"},
                {"id": "454", "name": "Rwanda", "category": "dxcc"},
                {"id": "456", "name": "Senegal", "category": "dxcc"},
                {"id": "458", "name": "Sierra Leone", "category": "dxcc"},
                {"id": "460", "name": "Rotuma I.", "category": "dxcc"},
                {"id": "462", "name": "South Africa", "category": "dxcc"},
                {"id": "464", "name": "Namibia", "category": "dxcc"},
                {"id": "466", "name": "Sudan", "category": "dxcc"},
                {"id": "468", "name": "Kingdom of Eswatini", "category": "dxcc"},
                {"id": "470", "name": "Tanzania", "category": "dxcc"},
                {"id": "474", "name": "Tunisia", "category": "dxcc"},
                {"id": "478", "name": "Egypt", "category": "dxcc"},
                {"id": "480", "name": "Burkina Faso", "category": "dxcc"},
                {"id": "482", "name": "Zambia", "category": "dxcc"},
                {"id": "483", "name": "Togo", "category": "dxcc"},
                {"id": "489", "name": "Conway Reef", "category": "dxcc"},
                {"id": "490", "name": "Banaba I.", "category": "dxcc"},
                {"id": "492", "name": "Yemen", "category": "dxcc"},
                {"id": "497", "name": "Croatia", "category": "dxcc"},
                {"id": "499", "name": "Slovenia", "category": "dxcc"},
                {"id": "501", "name": "Bosnia-Herzegovina", "category": "dxcc"},
                {"id": "502", "name": "North Macedonia", "category": "dxcc"},
                {"id": "503", "name": "Czech Republic", "category": "dxcc"},
                {"id": "504", "name": "Slovak Republic", "category": "dxcc"},
                {"id": "505", "name": "Pratas I.", "category": "dxcc"},
                {"id": "506", "name": "Scarborough Reef", "category": "dxcc"},
                {"id": "507", "name": "Temotu Province", "category": "dxcc"},
                {"id": "508", "name": "Austral I.", "category": "dxcc"},
                {"id": "509", "name": "Marquesas Is.", "category": "dxcc"},
                {"id": "510", "name": "Palestine", "category": "dxcc"},
                {"id": "511", "name": "Timor - Leste", "category": "dxcc"},
                {"id": "512", "name": "Chesterfield Is.", "category": "dxcc"},
                {"id": "513", "name": "Ducie I.", "category": "dxcc"},
                {"id": "514", "name": "Montenegro", "category": "dxcc"},
                {"id": "515", "name": "Swains I.", "category": "dxcc"},
                {"id": "516", "name": "Saint Barthelemy", "category": "dxcc"},
                {"id": "517", "name": "Curacao", "category": "dxcc"},
                {"id": "518", "name": "Sint Maarten", "category": "dxcc"},
                {"id": "519", "name": "Saba & St. Eustatius", "category": "dxcc"},
                {"id": "520", "name": "Bonaire", "category": "dxcc"},
                {"id": "521", "name": "South Sudan", "category": "dxcc"},
                {"id": "522", "name": "Republic of Kosovo", "category": "dxcc"}
            ]
        },
        "tiers": [
            {"id": "tier-50", "name": "50 Entities", "threshold": 50, "order": 1},
            {"id": "tier-100", "name": "DXCC", "threshold": 100, "order": 2},
            {"id": "tier-150", "name": "DXCC 150", "threshold": 150, "order": 3},
            {"id": "tier-200", "name": "DXCC 200", "threshold": 200, "order": 4},
            {"id": "tier-250", "name": "DXCC 250", "threshold": 250, "order": 5},
            {"id": "tier-300", "name": "DXCC 300", "threshold": 300, "order": 6},
            {"id": "tier-honor", "name": "DXCC Honor Roll", "threshold": 331, "order": 7}
        ],
        "qualificationCriteria": {
            "bands": null,
            "modes": null,
            "requiredFields": [],
            "dateRange": null,
            "matchRules": [
                {
                    "qsoField": "dxccEntity",
                    "goalField": "id",
                    "transformation": "none"
                }
            ]
        },
        "historicalQsosAllowed": true,
        "scoring": {
            "method": "count",
            "tiebreaker": "earliestCompletion",
            "displayFormat": "{value} entities"
        }
    }',
    true
)
ON CONFLICT (id) DO NOTHING;
